// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD88t8U3MV3l9Jx-fbCH-tW44OSnq3azVQ',
    appId: '1:398220662642:web:c35f6dd48725bc3f082feb',
    messagingSenderId: '398220662642',
    projectId: 'iot-training-final-project',
    authDomain: 'iot-training-final-project.firebaseapp.com',
    databaseURL: 'https://iot-training-final-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iot-training-final-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFtgk-FysXe3GTWVwTRvGILe9bBxRO8-A',
    appId: '1:398220662642:android:aa1153b92f5aa303082feb',
    messagingSenderId: '398220662642',
    projectId: 'iot-training-final-project',
    databaseURL: 'https://iot-training-final-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iot-training-final-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS2N4r6OZsaF4g9GVqegm9_PRHJRGGI0U',
    appId: '1:398220662642:ios:1450035403522fd4082feb',
    messagingSenderId: '398220662642',
    projectId: 'iot-training-final-project',
    databaseURL: 'https://iot-training-final-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iot-training-final-project.appspot.com',
    iosClientId: '398220662642-5d0th3cj27c50oo535rq502nlpgloarl.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS2N4r6OZsaF4g9GVqegm9_PRHJRGGI0U',
    appId: '1:398220662642:ios:06cfc6669f1d1f12082feb',
    messagingSenderId: '398220662642',
    projectId: 'iot-training-final-project',
    databaseURL: 'https://iot-training-final-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iot-training-final-project.appspot.com',
    iosClientId: '398220662642-ej579hkjlbk5rc8f205ru3u16jlliei5.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject.RunnerTests',
  );
}
